### ISSUE TITLE
Ночівля

### ISSUE THREAD

**Issue by mikeuse** [andkohut/Hello-World-1-#5]
Готель Chalet du Mont - дуже гарний та комфортний.
Безкоштовні сніданки та Wifi.

**Comment by andkohut** [comment]
### Chalet du Mont розташований на гірськолижному курорті Буковель. Гостям пропонують приладдя для приготування барбекю, дитячий ігровий майданчик, сонячну терасу, ресторан, бар і безкоштовну приватну автостоянку.

Номери оснащені телевізором з плоским екраном. У деяких номерах є зона відпочинку, у деяких - тераса або балкон. Гостям надають халати і тапочки. На всій території готелю Chalet du Mont надається безкоштовний Wi-Fi.

Стійка реєстрації працює цілодобово.

У готелі обладнано приміщення для зберігання лиж, пропонують оренду велосипедів. Гості можуть зайнятися різними видами активного відпочинку, зокрема лижним спортом і велоспортом. Відстань від готелю Chalet du Mont до гірськолижного підйомника "Витяг 2" становить 1 км, до гірськолижного підйомника "Витяг R2" - 1,1 км і до найближчого аеропорту в Івано-Франківську - 62 км. 


![изображение](https://user-images.githubusercontent.com/64063688/85752381-0cc9c480-b714-11ea-8b35-107620d9793d.png)

**Реєстрація заїзду** 
14:00 З 14:00 
Під час реєстрації заїзду гості зобов’язані пред’явити посвідчення особи та кредитну картку. 
**Реєстрація виїзду** 
12:00 До 12:00 


### Найпопулярніші зручності 
•	Басейн 
•	Безкоштовна парковка 
•	Безкоштовний Wi-Fi 
•	Оздоровчий спа-центр 
•	Сімейні номери 
•	Бар


**Спорт і відпочинок** 
•	Пряма трансляція спортивних ігор 
•	Жива музика/виступ 
•	Тематичні вечері 
•	Велосипедні екскурсії Оплачується окремо 
•	Вечірня розважальна програма 
•	Велоспорт Поза територією помешкання 
•	Піші прогулянки 
•	Прокат велосипедів (за додаткову плату) 
•	Більярд Оплачується окремо 
•	Дитячий майданчик 
•	Ігрова кімната 
•	Катання на лижах 

**Оздоровчі послуги** 
•	Басейн 
•	Басейн 
•	Роздягальня з шафками 
•	Фітнес 
•	Спа-лаунж/зона для релаксації 
•	Парова лазня 
•	Спа-процедури 
•	Сонячна парасоля 
•	Пляжне крісло/шезлонг 
•	Рушники для басейну/пляжу 
•	Басейн з соленою водою 
•	Басейн з підігрівом 
•	Басейн з видом 
•	Критий басейн (працює цілий рік) 
•	Критий плавальний басейн 
•	Масаж Оплачується окремо 
•	Оздоровчий спа-центр 
•	Фітнес-центр 


### Стандарт двомісний:
Сніданок 
Мило, шампунь
Халат
Фен
Душ
Вішалка для одягу
Звукоізоляція
Опалення
Сейф
Безкоштовний Wi-Fi
Тапочки
Постільна білизна
Рушники: 3 на особу
Холодильник
Телевізор
Балкон

![изображение](https://user-images.githubusercontent.com/64063688/85758346-e8bcb200-b718-11ea-89db-6ed01b81b6bf.png)

**Можливі варіанти - альтернативні або запасні**
У випадку форс-мажорних обставин, або ж як альтернатива,  є можливість зупинитися у готелях, що знаходяться поруч. На приклад:
### 1.	Gold Palace (за 450 м від Chalet du Mont)
Вартість від 900 грн за добу
Сніданок входить у вартість

![изображение](https://user-images.githubusercontent.com/64063688/85758715-3df8c380-b719-11ea-9e94-294e037800dd.png)

### 
### 2.	Альпін Готель (за 300 м від Chalet du Mont)
Вартість від 500 грн за добу
Сніданок входить у вартість

![изображение](https://user-images.githubusercontent.com/64063688/85758831-5832a180-b719-11ea-8e4f-4147448d7192.png)
